project_name: push_pull
run_name: push_pull

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 200
test_batch_size: 200 
epochs: 100
device: "cuda:0"
num_workers: 10
lr: 1e-4
x_min: 0
x_max: 10
y_min: -2
y_max: 2
optimizer: adamw
threshold: 0.5




# model params

encoding_size: 256
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]

# diffusion model params
num_diffusion_iters: 10

# context
context_type: temporal
context_size: 1 # 5

# action output params
len_traj_pred: 16
learn_angle: False

# dataset specific parameters
image_size: [224, 224] # width, height



carla:
  input_dir: /home/wzm/data/carla/120_256_256_5_whether
  output_dir: ./data/carla
  end_slack: 0 
  IMAGE_TOPIC: /carla/ego_vehicle/rgb_front/image
  ODOM_TOPIC: /carla/ego_vehicle/odometry
  img_process_func: process_wzm_img
  odom_process_func: nav_to_xy_yaw
  down_rate: 1
  waypoint_spacing: 2
  ang_offset: 0
bionic:
  input_dir: /media/wzm/新加卷/data/bionic
  output_dir: ./data/bionic
  img_process_func: process_wzm_img
  odom_process_func: nav_to_xy_yaw
  end_slack: 2 # because many trajectories end in collisions
  IMAGE_TOPIC: /dalsa_rgb/left/image_raw
  ODOM_TOPIC: /odom
  down_rate: 1
  waypoint_spacing: 4
  ang_offset: 0
zju:
  output_dir: ./data/zju
  end_slack: 2 # because many trajectories end in collisions
  IMAGE_TOPIC: /dalsa_rgb/left/image_raw
  ODOM_TOPIC: /odom
  down_rate: 1
  waypoint_spacing: 2
  ang_offset: 0

red_test:
  input_dir: /home/wzm/data/real_casia/red_test
  output_dir: ./data/red_test
  data_folder: ./pass
  end_slack: 2 # because many trajectories end in collisions
  IMAGE_TOPIC: /galaxy_camera/galaxy_camera/image_raw/compressed
  ODOM_TOPIC: /odom
  img_process_func: process_daheng_img
  odom_process_func: nav_to_xy_yaw
  down_rate: 1
  waypoint_spacing: 5
  ang_offset: 0

casia_rgb:
  input_dir: /home/wzm/data/real_casia/rgb/rgb_test
  output_dir: ./data/rgb_test
  data_folder: ./pass
  end_slack: 2 # because many trajectories end in collisions
  IMAGE_TOPIC: /camera/color/image_raw/compressed
  ODOM_TOPIC: /odom
  img_process_func: process_daheng_img
  odom_process_func: nav_to_xy_yaw
  down_rate: 1
  waypoint_spacing: 12
  ang_offset: 0

rgb_loop:
  input_dir: /home/wzm/data/real_casia/rgb_loop
  output_dir: ./data/rgb_loop
  data_folder: ./pass
  end_slack: 2 # because many trajectories end in collisions
  IMAGE_TOPIC: /camera/color/image_raw/compressed
  ODOM_TOPIC: /odom
  img_process_func: process_daheng_img
  odom_process_func: nav_to_xy_yaw
  down_rate: 1
  waypoint_spacing: 12
  ang_offset: 0

tartan_drive:
  input_dir: /home/wzm/data/CTIP_data/tartan_drive
  output_dir: ./data/tartan_drive
  data_folder: ./pass
  end_slack: 2 # because many trajectories end in collisions
  IMAGE_TOPIC: /multisense/left/image_rect_color
  ODOM_TOPIC: /odometry/filtered_odom
  img_process_func: process_tartan_img
  odom_process_func: nav_to_xy_yaw
  down_rate: 1
  waypoint_spacing: 12
  ang_offset: 1.5707963267948966 # pi/2

SACSoN:
  input_dir: /home/wzm/data/CTIP_data/SACSoN
  output_dir: ./data/SACSoN
  data_folder: ./pass
  end_slack: 17 # because many trajectories end in collisions
  IMAGE_TOPIC: /fisheye_image/compressed
  ODOM_TOPIC: /odometry
  img_process_func: process_scand_img
  odom_process_func: nav_to_xy_yaw
  down_rate: 1
  waypoint_spacing: 2
  ang_offset: 0

nclt:
  output_dir: ./data/nclt
  data_folder: ./pass
  end_slack: 5 # because many trajectories end in collisions
  down_rate: 2
  waypoint_spacing: 1
  ang_offset: 0

CONTROL_TOPIC: cmd_vel
# CARLA_TWIST_TOPIC: /carla/ego_vehicle/twist
KESHIHUA_TOPIC: /keshihua
ros_rate: 5
posi_waypoints_topic: /posi_waypoints
nega_waypoints_topic: /nega_waypoints
ckpt_path: logs/casia/0_5model_100.pt