project_name: push_pull
run_name: push_pull

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 200
test_batch_size: 200   # 这有用 
epochs: 100
device: "cuda:0"
num_workers: 10
lr: 1e-3
min_x: 0
max_x: 20
min_y: -10
max_y: 10
optimizer: adamw


# model params
ckpt_path: logs/05_18_20_55_48/models/best.pt
encoding_size: 256
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]

# diffusion model params
num_diffusion_iters: 10

# context
context_type: temporal
context_size: 1 # 5

# action output params
len_traj_pred: 16
learn_angle: False

# dataset specific parameters
image_size: [224, 224] # width, height



carla:
  data_folder: ./data/120_256_256_10hz_posi
  end_slack: 2 # because many trajectories end in collisions
  IMAGE_TOPIC: /carla/ego_vehicle/rgb_front/image
  ODOM_TOPIC: /carla/ego_vehicle/odometry
bionic:
  input_dir: /media/wzm/新加卷/data/bionic
  output_dir: ./data/bionic
  img_process_func: process_wzm_img
  odom_process_func: nav_to_xy_yaw
  end_slack: 2 # because many trajectories end in collisions
  IMAGE_TOPIC: /dalsa_rgb/left/image_raw
  ODOM_TOPIC: /odom
  down_rate: 1
  waypoint_spacing: 5

CARLA_TWIST_TOPIC: /carla/ego_vehicle/twist
KESHIHUA_TOPIC: /keshihua
vel_recovery_topic: /cmd_vel_mux/input/recovery
ros_rate: 5
posi_waypoints_topic: /posi_waypoints
nega_waypoints_topic: /nega_waypoints